# Generated by Django 3.1.14 on 2022-05-23 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_auto_20220520_0847'),
        ('shop', '0017_auto_20220520_0821'),
    ]

    operations = [
    ]
